version: "3"
services:

  app:
    platform: linux/amd64
    container_name: hospital-front
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    # restart: on-failure

