version: "3"
services:
  app:
    # platform: linux/amd64
    build: .
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=docker
    networks:
      - backend-java_vivi-blog
    # restart: on-failure
networks:
  backend-java_vivi-blog:
    driver: bridge
